spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/ranking_db?options=-c%20TimeZone%3DUTC
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data_extra.sql

spring.jpa.show-sql=true